// ~/adam-backend/supabase/functions/generatePdf/index.ts
// Minimal PDF generator for Supabase Edge Functions (Deno)

// pdf-lib works in Deno via esm.sh
import {
  PDFDocument,
  StandardFonts,
  rgb,
} from "https://esm.sh/pdf-lib@1.17.1";

type RequestBody = {
  title?: string;
  lines?: (string | number)[];
};

Deno.serve(async (req: Request) => {
  try {
    if (req.method !== "POST") {
      return new Response("Use POST", { status: 405 });
    }

    const body = (await req.json().catch(() => ({}))) as RequestBody;
    const title = (body.title ?? "Generated PDF") + "";
    const lines = Array.isArray(body.lines) ? body.lines : [];

    const pdf = await PDFDocument.create();
    const pageWidth = 595.28;  // A4 width (points)
    const pageHeight = 841.89; // A4 height (points)
    let page = pdf.addPage([pageWidth, pageHeight]);

    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);

    // Header
    page.drawText("Andy’K Group International", {
      x: 50,
      y: pageHeight - 50,
      size: 10,
      font: fontBold,
      color: rgb(0.16, 0.16, 0.16),
    });

    // Title
    page.drawText(title, {
      x: 50,
      y: pageHeight - 90,
      size: 22,
      font: fontBold,
      color: rgb(0.1, 0.1, 0.1),
    });

    // Divider
    page.drawLine({
      start: { x: 50, y: pageHeight - 100 },
      end: { x: pageWidth - 50, y: pageHeight - 100 },
      thickness: 1,
      color: rgb(0.83, 0.69, 0.22), // gold-ish
    });

    // Body lines
    let y = pageHeight - 130;
    const lineHeight = 18;

    const writeLine = (text: string) => {
      page.drawText(text, {
        x: 50,
        y,
        size: 12,
        font,
        color: rgb(0, 0, 0),
      });
    };

    for (const raw of lines) {
      const text = String(raw ?? "");
      if (y < 60) {
        // new page
        page = pdf.addPage([pageWidth, pageHeight]);
        y = pageHeight - 60;
      }
      writeLine(text);
      y -= lineHeight;
    }

    // Footer
    page.drawText("Generated by A.D.A.M. • " + new Date().toISOString(), {
      x: 50,
      y: 30,
      size: 9,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });

    const bytes = await pdf.save();

    return new Response(bytes, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": 'inline; filename="generated.pdf"',
      },
    });
  } catch (err) {
    console.error(err);
    return new Response(
      JSON.stringify({ error: "PDF generation failed", detail: String(err) }),
      { status: 500, headers: { "Content-Type": "application/json" } }
    );
  }
});
